### ISSUE TITLE
Some suggested papers from ICCV 2019

### ISSUE THREAD

**Issue by karnival** [AgaMiko/data-augmentation-review#1]
Nice work on the repo!

I wanted to suggest a couple of papers from ICCV 2019 you might want to add:

* `Occlusions for Effective Data Augmentation in Image Classification` https://arxiv.org/abs/1910.10651

* `CutMix: Regularization Strategy to Train Strong Classifiers with Localizable Features`
https://arxiv.org/abs/1905.04899

**Comment by AgaMiko** [comment]
Hello David,
Thank you for a very useful suggestion! I have added the following papers to the repo.
Best,
Agnieszka
