### ISSUE TITLE
Initiating the Source Code Augmentation

### ISSUE THREAD

**Issue by terryyz** [AgaMiko/data-augmentation-review#14]
Hi Agnieszka!

We're building [a collection on the Data Augmentation for Code](https://github.com/terryyz/DataAug4Code) and have written a [survey](https://arxiv.org/abs/2305.19915) on this topic. Would love to see how we can bring our findings to this awesome repo 🤗 

Cheers,
Terry

**Comment by AgaMiko** [comment]
Hi Terry, Feel free to create a PR if you feel something is missing!
