### ISSUE TITLE
WB augmenter — suggested work from ICCV’19

### ISSUE THREAD

**Issue by mahmoudnafifi** [AgaMiko/data-augmentation-review#4]
Thanks for the great effort!

I want to suggest our WB augmentation to be added to your list.

Paper: https://arxiv.org/pdf/1912.06960.pdf 
Github repo: https://github.com/mahmoudnafifi/WB_color_augmenter

Thanks!

**Comment by AgaMiko** [comment]
Thanks for the recommendation.
Added your repo and paper to the list.
