### ISSUE TITLE
One suggested paper from ECCV 2020

### ISSUE THREAD

**Issue by zhiqiangdon** [AgaMiko/data-augmentation-review#6]
Hi,

Awesome data augmentation collections!

It would be great if you can add a new paper, "OnlineAugment: Online Data Augmentation with Less Domain Knowledge" from ECCV 2020. Here are the links:
 
Github repo: [https://github.com/zhiqiangdon/online-augment](url)
Paper link: [https://arxiv.org/pdf/2007.09271.pdf](url)

This paper proposes more general augmentations, which do not use image preprocessing operations. It is more automatic than AutoAugment and related as it does not require much domain knowledge to specify the operations and their ranges. Besides, it is very easy to use (one stage training in one GPU).

Thanks!

**Comment by AgaMiko** [comment]
Hello @zhiqiangdon,

Thanks for recommending your paper and repo! It seems to be a great and valuable resource. I've added it in the last commit.

Best,
Agnieszka

**Comment by zhiqiangdon** [comment]
Thanks, @AgaMiko!
